### ISSUE TITLE
Different Categories for Bookmarks and Autosave for Recent

### ISSUE THREAD

**Issue by mortyobnoxious** [NurioHin/mpv-bookmarker#12]
Hi is it possible to have different categories for bookmarks? For example:
```
Category 1 Movies:
    - Movie 1
    - Movie 2
Category 2 Series:
    - Series 1
    - Series 2
Category 3 Youtube:
    - Youtube 1
    - Youtube 2
Category 4 Recent Files:
    - Recent 1
    - Recent 2
```

So basically there will be different categories for bookmarking and an option to auto-save all recently played files to "recent files" category.

I know I'm asking too much but this would be great.

**Comment by DevinMadsen** [comment]
This seems like two seperate requests. They should really be in seperate issues. The recent files might be something that someone has done before in a different mpv script it seems out of scope for this script. I might be able to implement the categories for you. It would be easier with an external script though. My first question would be what OS do you use?

**Comment by mortyobnoxious** [comment]
Oh sorry I thought they would go well together since _recent files_ will be just another category. But apparently not.

I'm on Windows.

**Comment by DevinMadsen** [comment]
Maybe I'm misunderstanding, would you want the recent files to just be bookmarked at the beginning of the video?

**Comment by mortyobnoxious** [comment]
At the beginning, when paused or on quit. Whichever is possible. It will just save recently opened files directly to recent files category.

Maybe this sounded weird because I really don't use "timestamps/jump to timestamp/time-pos" because mpv does save where I left with the video(with **write_watch_later** or **save-position-on-quit** I'm not sure.).

I just use bookmarking for **file name** and **url**.
