### ISSUE TITLE
Infinite Scrolling on Menu by Disabling Pagination

### ISSUE THREAD

**Issue by mortyobnoxious** [NurioHin/mpv-bookmarker#13]
Is there a way to disable "page" feature and have infinite scrolling through all items in the menu?

Like this from [mpv-playlistmanager](/jonniek/mpv-playlistmanager):

![ByOhcXSMEk](https://user-images.githubusercontent.com/42044258/127761915-8a4dce5d-1647-43f1-9b45-676f0b8bbf60.gif)

**Comment by Rotvie** [comment]
I'd like this too!

**Comment by Rotvie** [comment]
@mortyobnoxious Did you manage to get this feature?

**Comment by mortyobnoxious** [comment]
@Rotvie Nope!
I closed the issue because I didn't think it will be completed.

**Comment by NurioHin** [comment]
Sorry, I haven't been on Github in ages! I just happened to come back here, and I'll look into this when I have time

**Comment by Rotvie** [comment]
@NurioHin Thanks!
