### ISSUE TITLE
special/unicode characters in filename disrupt loading

### ISSUE THREAD

**Issue by elig0n** [NurioHin/mpv-bookmarker#3]
special unicode characters or foreign language character sets such as `🛑` or `Č` that appears in filenames prevents letting the script load the file i.e. `Can't find file for bookmark ....`

**Comment by NurioHin** [comment]
I cannot replicate this bug. As a test, I named a file `Č.mkv` and bookmarked it, closed mpv, and then loaded that bookmark, and everything worked fine. Are you using Windows, and if so, is your Windows codepage set to UTF-8? You can check by running `cmd.exe` and executing `chcp`. The codepage should be 65001

**Comment by elig0n** [comment]
Code page is different, but even after running `chcp 65001` in cmd and running mpv right after it the error remains (I bookmarked new and then tried to load it).

<img src="https://i.ibb.co/zrgt4zF/bkm.png">

**Comment by NurioHin** [comment]
I am not sure what to tell you. It seems to be working fine on my system:

![image](https://user-images.githubusercontent.com/18533703/97770340-a5dd7180-1b32-11eb-82eb-f4f48c8dcd8e.png)

And I don't mean that in a way of "Works on my system; it's your problem". But if I can't even replicate this problem, it'll be impossible for me to fix it, as much as I'd want to

**Comment by mochaaP** [comment]
I can replicate this problem too.

![winver.exe](https://user-images.githubusercontent.com/21154023/98460552-6c66cf00-21e0-11eb-996a-30f17b3238fa.png)
![mpv.net](https://user-images.githubusercontent.com/21154023/98460619-ea2ada80-21e0-11eb-940d-f620fd1c3caf.png)

Running on Windows 10 2004 zh-CN, default codepage is `936`, setting it to 65001 doesn't make it work either.

A tempfix (replace the original function) that works for me:

```lua
function fileExists(path)
  local f = utils.file_info(path)
  return f.is_file
end
```

I guess we can rewrite the path related helper functions, as they are old and dirty (e.g. `getFilepath()` will only return `%AppData%/mpv` but not `portable_config`)?

**Comment by mochaaP** [comment]
I can replicate this problem too.

![winver.exe](https://user-images.githubusercontent.com/21154023/98460552-6c66cf00-21e0-11eb-996a-30f17b3238fa.png)
![mpv.net](https://user-images.githubusercontent.com/21154023/98460619-ea2ada80-21e0-11eb-940d-f620fd1c3caf.png)

Running on Windows 10 2004 zh-CN, default codepage is `936`, setting it to 65001 doesn't make it work either.

A tempfix (replace the original function):

```lua
function fileExists(path)
  local f = utils.file_info(path)
  return f.is_file
end
```

I guess we can rewrite the path related helper functions, as they are old and dirty (e.g. `getFilepath(` will only use `%AppData%/mpv` but not `portable_config`)?

**Comment by elig0n** [comment]
@NurioHin ^

**Comment by mochaaP** [comment]
@elig0n Hey, thanks for the notification, just rewrote some helper functions (logic from <https://github.com/VideoPlayerCode/mpv-tools>, I just rewrote them in Lua) and here's a patch:

```lua
-- // General utilities \\ --

local _isUnix, _isMac, _pathSep

function _detectOS() -- from VideoPlayerCode/modules.js/PathTools.js
  -- Detect Unix/Linux/macOS if the path starts with a forward slash.
  _isUnix = string.sub(utils.getcwd(), 1, 1) == '/'
  _isMac = false -- Mac is also Unix, but we'll detect separately.
  _pathSep = _isUnix and '/' or '\\'

  if _isUnix then
    local unameResult = utils.command_native({
      name = "subprocess",
      args = {"uname", "-s"},
      cancellable = false,
      capture_stdout = true
    })
    if unameResult:match "^%s*Darwin%s*$" then
      _isMac = true
    end
  end
end

-- Check if the operating system is Mac OS
function isMac()
  if _isMac == nil then
    _detectOS()
  end
  return _isMac
end

-- Check if the operating system is Windows
function isWindows()
  if _isUnix == nil then
    _detectOS()
  end
  return not _isUnix
end

-- Check whether a certain file exists
function fileExists(path)
  local f = utils.file_info(path)
  return f.is_file
end

-- Get the filepath of a file from the mpv config folder
function getFilepath(filename)
  return mp.command_native({"expand-path", "~~/" .. filename})
end
```

Hope it works ;)

**Comment by mochaaP** [comment]
Ready for review.
